server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-name: Web App Client
            client-id: webappclient
            client-secret: webappclientsecret
            scope: resource.read,resource.write,openid,profile
        provider:
          uaa:
            issuer-uri: http://localhost:8080/uaa/oauth/token
resource:
  server:
    url: http://localhost:8082